#! /bin/bash
logger -i -t PlayspotConfig Resetting HCI 
hciconfig hci0 reset
hciconfig hci0 up
logger -i -t PlayspotConfig Starting Playspot Service 
exec ./PlayspotConfiguration >& /var/log/playspot
